sudo: required

language: generic

services:
  - docker

before_install:
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
 # - docker login -u="$HEROKUUSER" -p="$HEROKUPASS" $HEROKUREPO

install:
  - travis_wait 30 docker build -t qualicen/spacyapi:base_v2 .
#  - travis_wait 30 docker build -t qualicen/spacyapi:en_v2 -f docker/en/Dockerfile .
  - travis_wait 30 docker build -t qualicen/spacyapi:en_v2_lg -f docker/en/Dockerfile.lg .
#  - travis_wait 30 docker build -t qualicen/spacyapi:en_v2_md -f docker/en/Dockerfile.md .
#  - travis_wait 30 docker build -t qualicen/spacyapi:de_v2 -f docker/de/Dockerfile .
#  - travis_wait 30 docker build -t qualicen/spacyapi:es_v2 -f docker/es/Dockerfile .
#  - travis_wait 30 docker build -t qualicen/spacyapi:fr_v2 -f docker/fr/Dockerfile .
#  - travis_wait 30 docker build -t qualicen/spacyapi:nl_v2 -f docker/nl/Dockerfile .
#  - travis_wait 30 docker build -t qualicen/spacyapi:pt_v2 -f docker/pt/Dockerfile .
#  - travis_wait 30 docker build -t qualicen/spacyapi:it_v2 -f docker/it/Dockerfile .
#  - travis_wait 30 docker build -t qualicen/spacyapi:all_v2 -f docker/all/Dockerfile .

after_success:
  - docker push qualicen/spacyapi:base_v2
#  - docker push qualicen/spacyapi:en_v2
  - docker push qualicen/spacyapi:en_v2_lg
 # - docker push qualicen/spacyapi:en_v2_md
 # - docker push qualicen/spacyapi:de_v2
 # - docker push qualicen/spacyapi:es_v2
 # - docker push qualicen/spacyapi:fr_v2
 # - docker push qualicen/spacyapi:pt_v2
 # - docker push qualicen/spacyapi:it_v2
 # - docker push qualicen/spacyapi:nl_v2
 # - docker push qualicen/spacyapi:all_v2
 # - docker tag qualicen/spacyapi:en_v2 registry.heroku.com/spacy-en/web
 # - docker push registry.heroku.com/spacy-en/web
 # - docker tag qualicen/spacyapi:de_v2 registry.heroku.com/spacy-de/web
 # - docker push registry.heroku.com/spacy-de/web
